// ============ Popcorn movie catalog ============
//
// A curated set of well-known movies used for:
//  - autocomplete when adding movies to your Favorites list
//  - the recommendation engine's candidate pool
//  - the Sampler (well-known movies suggested to rate)
//
// Fields (kept short since this file is hand-authored):
//   id  - stable slug, used as the unique key everywhere
//   t   - title
//   y   - release year
//   g   - genres (controlled vocabulary, see GENRES below)
//   tg  - style/mood tags (controlled vocabulary, see TAGS below)
//   p   - rough popularity score 1-100, used as a sampler weight and score tiebreaker

const GENRES = [
  "Action", "Adventure", "Animation", "Comedy", "Crime", "Drama", "Fantasy",
  "Horror", "Mystery", "Romance", "SciFi", "Thriller", "War", "Western",
  "Musical", "Documentary", "Family", "Biography", "Sport", "History",
];

const TAGS = [
  "dark", "feelgood", "twist-ending", "based-on-true-story", "ensemble-cast",
  "visually-stunning", "slow-burn", "fast-paced", "cult-classic",
  "award-winning", "coming-of-age", "dystopian", "heist", "courtroom",
  "road-trip", "psychological", "epic", "indie", "superhero", "time-travel",
  "revenge", "redemption", "satire", "noir", "apocalyptic", "underdog",
  "spy", "prison", "musical-numbers", "mind-bending", "nonlinear",
];

const MOVIES = [
  { id: "shawshank", t: "The Shawshank Redemption", y: 1994, g: ["Drama", "Crime"], tg: ["prison", "redemption", "slow-burn", "award-winning"], p: 99 },
  { id: "godfather", t: "The Godfather", y: 1972, g: ["Crime", "Drama"], tg: ["epic", "award-winning", "ensemble-cast"], p: 98 },
  { id: "godfather2", t: "The Godfather Part II", y: 1974, g: ["Crime", "Drama"], tg: ["epic", "award-winning", "ensemble-cast"], p: 92 },
  { id: "goodfellas", t: "Goodfellas", y: 1990, g: ["Crime", "Drama", "Biography"], tg: ["fast-paced", "based-on-true-story", "cult-classic"], p: 91 },
  { id: "pulpfiction", t: "Pulp Fiction", y: 1994, g: ["Crime", "Drama"], tg: ["ensemble-cast", "dark", "cult-classic", "nonlinear"], p: 96 },
  { id: "fightclub", t: "Fight Club", y: 1999, g: ["Drama", "Thriller"], tg: ["twist-ending", "dark", "cult-classic", "psychological"], p: 93 },
  { id: "departed", t: "The Departed", y: 2006, g: ["Crime", "Drama", "Thriller"], tg: ["twist-ending", "fast-paced", "award-winning"], p: 89 },
  { id: "nocountry", t: "No Country for Old Men", y: 2007, g: ["Crime", "Thriller", "Western"], tg: ["dark", "slow-burn", "award-winning"], p: 86 },
  { id: "seven", t: "Se7en", y: 1995, g: ["Crime", "Thriller", "Mystery"], tg: ["dark", "twist-ending", "psychological"], p: 88 },
  { id: "ahx", t: "American History X", y: 1998, g: ["Drama", "Crime"], tg: ["dark", "redemption", "psychological"], p: 84 },
  { id: "cityofgod", t: "City of God", y: 2002, g: ["Crime", "Drama"], tg: ["ensemble-cast", "based-on-true-story", "fast-paced"], p: 82 },
  { id: "scarface", t: "Scarface", y: 1983, g: ["Crime", "Drama"], tg: ["epic", "cult-classic", "revenge"], p: 83 },
  { id: "casino", t: "Casino", y: 1995, g: ["Crime", "Drama"], tg: ["epic", "based-on-true-story"], p: 78 },
  { id: "wolfwallst", t: "The Wolf of Wall Street", y: 2013, g: ["Crime", "Comedy", "Biography"], tg: ["fast-paced", "based-on-true-story", "satire"], p: 90 },
  { id: "reservoirdogs", t: "Reservoir Dogs", y: 1992, g: ["Crime", "Thriller"], tg: ["ensemble-cast", "dark", "cult-classic", "nonlinear"], p: 79 },
  { id: "clockworkorange", t: "A Clockwork Orange", y: 1971, g: ["Crime", "Drama", "SciFi"], tg: ["dark", "cult-classic", "psychological", "dystopian"], p: 80 },
  { id: "therewillbeblood", t: "There Will Be Blood", y: 2007, g: ["Drama"], tg: ["slow-burn", "dark", "award-winning"], p: 81 },
  { id: "silenceofthelambs", t: "The Silence of the Lambs", y: 1991, g: ["Thriller", "Horror", "Crime"], tg: ["psychological", "dark", "award-winning"], p: 90 },
  { id: "prisoners", t: "Prisoners", y: 2013, g: ["Crime", "Thriller", "Mystery"], tg: ["dark", "slow-burn", "twist-ending"], p: 79 },
  { id: "nightcrawler", t: "Nightcrawler", y: 2014, g: ["Crime", "Thriller", "Drama"], tg: ["dark", "psychological", "indie"], p: 78 },
  { id: "gonegirl", t: "Gone Girl", y: 2014, g: ["Mystery", "Thriller", "Drama"], tg: ["twist-ending", "dark", "psychological"], p: 85 },

  { id: "matrix", t: "The Matrix", y: 1999, g: ["SciFi", "Action"], tg: ["mind-bending", "cult-classic", "fast-paced", "visually-stunning"], p: 96 },
  { id: "inception", t: "Inception", y: 2010, g: ["SciFi", "Action", "Thriller"], tg: ["mind-bending", "visually-stunning", "twist-ending"], p: 95 },
  { id: "interstellar", t: "Interstellar", y: 2014, g: ["SciFi", "Drama", "Adventure"], tg: ["visually-stunning", "epic", "mind-bending"], p: 94 },
  { id: "bladerunner", t: "Blade Runner", y: 1982, g: ["SciFi", "Thriller"], tg: ["dystopian", "slow-burn", "cult-classic", "visually-stunning"], p: 84 },
  { id: "bladerunner2049", t: "Blade Runner 2049", y: 2017, g: ["SciFi", "Thriller"], tg: ["dystopian", "slow-burn", "visually-stunning"], p: 82 },
  { id: "arrival", t: "Arrival", y: 2016, g: ["SciFi", "Drama", "Mystery"], tg: ["slow-burn", "mind-bending", "award-winning"], p: 84 },
  { id: "exmachina", t: "Ex Machina", y: 2014, g: ["SciFi", "Thriller"], tg: ["psychological", "mind-bending", "indie"], p: 80 },
  { id: "terminator", t: "The Terminator", y: 1984, g: ["SciFi", "Action"], tg: ["cult-classic", "fast-paced", "dystopian"], p: 85 },
  { id: "terminator2", t: "Terminator 2: Judgment Day", y: 1991, g: ["SciFi", "Action"], tg: ["fast-paced", "epic", "cult-classic"], p: 89 },
  { id: "alien", t: "Alien", y: 1979, g: ["SciFi", "Horror"], tg: ["dark", "slow-burn", "cult-classic"], p: 88 },
  { id: "aliens", t: "Aliens", y: 1986, g: ["SciFi", "Action", "Horror"], tg: ["fast-paced", "ensemble-cast", "cult-classic"], p: 85 },
  { id: "starwars4", t: "Star Wars: A New Hope", y: 1977, g: ["SciFi", "Adventure", "Fantasy"], tg: ["epic", "cult-classic", "underdog"], p: 95 },
  { id: "starwars5", t: "The Empire Strikes Back", y: 1980, g: ["SciFi", "Adventure", "Fantasy"], tg: ["epic", "twist-ending", "cult-classic"], p: 95 },
  { id: "starwars7", t: "Star Wars: The Force Awakens", y: 2015, g: ["SciFi", "Adventure"], tg: ["epic", "fast-paced"], p: 88 },
  { id: "et", t: "E.T. the Extra-Terrestrial", y: 1982, g: ["SciFi", "Family", "Adventure"], tg: ["feelgood", "coming-of-age", "cult-classic"], p: 86 },
  { id: "backtothefuture", t: "Back to the Future", y: 1985, g: ["SciFi", "Comedy", "Adventure"], tg: ["time-travel", "feelgood", "cult-classic"], p: 93 },
  { id: "minorityreport", t: "Minority Report", y: 2002, g: ["SciFi", "Action", "Mystery"], tg: ["dystopian", "twist-ending", "fast-paced"], p: 78 },
  { id: "district9", t: "District 9", y: 2009, g: ["SciFi", "Action", "Thriller"], tg: ["dystopian", "indie", "fast-paced"], p: 79 },
  { id: "edgeoftomorrow", t: "Edge of Tomorrow", y: 2014, g: ["SciFi", "Action"], tg: ["time-travel", "fast-paced"], p: 80 },
  { id: "gravity", t: "Gravity", y: 2013, g: ["SciFi", "Thriller", "Drama"], tg: ["visually-stunning", "slow-burn", "award-winning"], p: 81 },
  { id: "themartian", t: "The Martian", y: 2015, g: ["SciFi", "Drama", "Adventure"], tg: ["feelgood", "underdog", "visually-stunning"], p: 85 },
  { id: "dune", t: "Dune", y: 2021, g: ["SciFi", "Adventure", "Drama"], tg: ["epic", "visually-stunning", "slow-burn"], p: 89 },
  { id: "dune2", t: "Dune: Part Two", y: 2024, g: ["SciFi", "Adventure", "Drama"], tg: ["epic", "visually-stunning", "fast-paced"], p: 90 },
  { id: "2001", t: "2001: A Space Odyssey", y: 1968, g: ["SciFi", "Drama"], tg: ["slow-burn", "mind-bending", "visually-stunning", "cult-classic"], p: 80 },
  { id: "childrenofmen", t: "Children of Men", y: 2006, g: ["SciFi", "Drama", "Thriller"], tg: ["dystopian", "slow-burn", "dark"], p: 76 },
  { id: "looper", t: "Looper", y: 2012, g: ["SciFi", "Action", "Thriller"], tg: ["time-travel", "mind-bending"], p: 78 },
  { id: "predestination", t: "Predestination", y: 2014, g: ["SciFi", "Thriller", "Mystery"], tg: ["time-travel", "twist-ending", "mind-bending", "indie"], p: 70 },
  { id: "her", t: "Her", y: 2013, g: ["SciFi", "Drama", "Romance"], tg: ["indie", "slow-burn", "award-winning"], p: 79 },
  { id: "readyplayerone", t: "Ready Player One", y: 2018, g: ["SciFi", "Action", "Adventure"], tg: ["visually-stunning", "fast-paced", "cult-classic"], p: 78 },
  { id: "jurassicpark", t: "Jurassic Park", y: 1993, g: ["SciFi", "Adventure", "Action"], tg: ["visually-stunning", "fast-paced", "cult-classic"], p: 92 },

  { id: "lotr1", t: "The Lord of the Rings: The Fellowship of the Ring", y: 2001, g: ["Fantasy", "Adventure"], tg: ["epic", "visually-stunning", "ensemble-cast"], p: 95 },
  { id: "lotr2", t: "The Lord of the Rings: The Two Towers", y: 2002, g: ["Fantasy", "Adventure"], tg: ["epic", "visually-stunning", "ensemble-cast"], p: 94 },
  { id: "lotr3", t: "The Lord of the Rings: The Return of the King", y: 2003, g: ["Fantasy", "Adventure"], tg: ["epic", "visually-stunning", "award-winning"], p: 96 },
  { id: "hobbit1", t: "The Hobbit: An Unexpected Journey", y: 2012, g: ["Fantasy", "Adventure"], tg: ["epic", "visually-stunning"], p: 81 },
  { id: "hp1", t: "Harry Potter and the Sorcerer's Stone", y: 2001, g: ["Fantasy", "Adventure", "Family"], tg: ["coming-of-age", "feelgood", "cult-classic"], p: 89 },
  { id: "panslabyrinth", t: "Pan's Labyrinth", y: 2006, g: ["Fantasy", "Drama", "Horror"], tg: ["dark", "visually-stunning", "award-winning"], p: 80 },
  { id: "princessbride", t: "The Princess Bride", y: 1987, g: ["Fantasy", "Adventure", "Romance", "Comedy"], tg: ["feelgood", "cult-classic", "satire"], p: 85 },
  { id: "indianajones", t: "Raiders of the Lost Ark", y: 1981, g: ["Action", "Adventure"], tg: ["fast-paced", "cult-classic", "epic"], p: 91 },
  { id: "poc1", t: "Pirates of the Caribbean: The Curse of the Black Pearl", y: 2003, g: ["Action", "Adventure", "Fantasy"], tg: ["fast-paced", "feelgood"], p: 87 },
  { id: "avatar", t: "Avatar", y: 2009, g: ["SciFi", "Adventure", "Action"], tg: ["visually-stunning", "epic"], p: 90 },

  { id: "darkknight", t: "The Dark Knight", y: 2008, g: ["Action", "Crime", "Thriller"], tg: ["superhero", "dark", "award-winning", "fast-paced"], p: 98 },
  { id: "batmanbegins", t: "Batman Begins", y: 2005, g: ["Action", "Crime"], tg: ["superhero", "dark", "epic"], p: 87 },
  { id: "avengers", t: "The Avengers", y: 2012, g: ["Action", "SciFi", "Adventure"], tg: ["superhero", "ensemble-cast", "fast-paced"], p: 91 },
  { id: "spiderversegh", t: "Spider-Man: Into the Spider-Verse", y: 2018, g: ["Animation", "Action", "Adventure"], tg: ["superhero", "visually-stunning", "award-winning"], p: 92 },
  { id: "ironman", t: "Iron Man", y: 2008, g: ["Action", "SciFi"], tg: ["superhero", "fast-paced", "satire"], p: 88 },
  { id: "logan", t: "Logan", y: 2017, g: ["Action", "Drama", "SciFi"], tg: ["superhero", "dark", "slow-burn"], p: 85 },
  { id: "guardians", t: "Guardians of the Galaxy", y: 2014, g: ["Action", "SciFi", "Comedy"], tg: ["superhero", "ensemble-cast", "feelgood"], p: 89 },
  { id: "blackpanther", t: "Black Panther", y: 2018, g: ["Action", "SciFi", "Adventure"], tg: ["superhero", "epic", "award-winning"], p: 88 },
  { id: "watchmen", t: "Watchmen", y: 2009, g: ["Action", "Thriller", "Mystery"], tg: ["superhero", "dark", "psychological"], p: 74 },
  { id: "joker", t: "Joker", y: 2019, g: ["Crime", "Drama", "Thriller"], tg: ["dark", "psychological", "award-winning"], p: 88 },

  { id: "toystory", t: "Toy Story", y: 1995, g: ["Animation", "Family", "Comedy"], tg: ["feelgood", "cult-classic"], p: 92 },
  { id: "toystory3", t: "Toy Story 3", y: 2010, g: ["Animation", "Family", "Comedy"], tg: ["feelgood", "award-winning"], p: 90 },
  { id: "findingnemo", t: "Finding Nemo", y: 2003, g: ["Animation", "Family", "Adventure"], tg: ["feelgood", "road-trip"], p: 89 },
  { id: "up", t: "Up", y: 2009, g: ["Animation", "Family", "Adventure"], tg: ["feelgood", "award-winning"], p: 90 },
  { id: "insideout", t: "Inside Out", y: 2015, g: ["Animation", "Family", "Comedy"], tg: ["feelgood", "award-winning"], p: 89 },
  { id: "coco", t: "Coco", y: 2017, g: ["Animation", "Family", "Fantasy"], tg: ["feelgood", "award-winning"], p: 88 },
  { id: "spiritedaway", t: "Spirited Away", y: 2001, g: ["Animation", "Fantasy", "Family"], tg: ["visually-stunning", "cult-classic", "award-winning"], p: 90 },
  { id: "totoro", t: "My Neighbor Totoro", y: 1988, g: ["Animation", "Family", "Fantasy"], tg: ["feelgood", "cult-classic"], p: 82 },
  { id: "lionking", t: "The Lion King", y: 1994, g: ["Animation", "Family", "Drama"], tg: ["feelgood", "epic", "cult-classic"], p: 92 },
  { id: "shrek", t: "Shrek", y: 2001, g: ["Animation", "Family", "Comedy"], tg: ["satire", "feelgood", "cult-classic"], p: 88 },
  { id: "walle", t: "WALL-E", y: 2008, g: ["Animation", "SciFi", "Family"], tg: ["feelgood", "dystopian", "award-winning"], p: 87 },
  { id: "httyd", t: "How to Train Your Dragon", y: 2010, g: ["Animation", "Family", "Adventure"], tg: ["feelgood", "coming-of-age"], p: 86 },
  { id: "zootopia", t: "Zootopia", y: 2016, g: ["Animation", "Family", "Mystery"], tg: ["feelgood", "satire"], p: 85 },
  { id: "incredibles", t: "The Incredibles", y: 2004, g: ["Animation", "Family", "Action"], tg: ["superhero", "feelgood"], p: 87 },
  { id: "ratatouille", t: "Ratatouille", y: 2007, g: ["Animation", "Family", "Comedy"], tg: ["feelgood", "underdog"], p: 85 },

  { id: "superbad", t: "Superbad", y: 2007, g: ["Comedy"], tg: ["coming-of-age", "fast-paced", "cult-classic"], p: 83 },
  { id: "bridesmaids", t: "Bridesmaids", y: 2011, g: ["Comedy"], tg: ["ensemble-cast", "feelgood"], p: 80 },
  { id: "grandbudapest", t: "The Grand Budapest Hotel", y: 2014, g: ["Comedy", "Drama"], tg: ["visually-stunning", "indie", "satire"], p: 84 },
  { id: "groundhogday", t: "Groundhog Day", y: 1993, g: ["Comedy", "Fantasy", "Romance"], tg: ["time-travel", "feelgood", "cult-classic"], p: 85 },
  { id: "anchorman", t: "Anchorman: The Legend of Ron Burgundy", y: 2004, g: ["Comedy"], tg: ["satire", "cult-classic"], p: 78 },
  { id: "hangover", t: "The Hangover", y: 2009, g: ["Comedy"], tg: ["fast-paced", "ensemble-cast", "road-trip"], p: 84 },
  { id: "knivesout", t: "Knives Out", y: 2019, g: ["Mystery", "Comedy", "Crime"], tg: ["twist-ending", "ensemble-cast", "satire"], p: 87 },
  { id: "meangirls", t: "Mean Girls", y: 2004, g: ["Comedy", "Drama"], tg: ["coming-of-age", "satire", "cult-classic"], p: 84 },
  { id: "ferrisbueller", t: "Ferris Bueller's Day Off", y: 1986, g: ["Comedy"], tg: ["coming-of-age", "feelgood", "cult-classic"], p: 83 },
  { id: "biglebowski", t: "The Big Lebowski", y: 1998, g: ["Comedy", "Crime"], tg: ["cult-classic", "satire", "indie"], p: 84 },

  { id: "thenotebook", t: "The Notebook", y: 2004, g: ["Romance", "Drama"], tg: ["feelgood", "based-on-true-story"], p: 84 },
  { id: "titanic", t: "Titanic", y: 1997, g: ["Romance", "Drama"], tg: ["epic", "based-on-true-story", "award-winning"], p: 94 },
  { id: "lalaland", t: "La La Land", y: 2016, g: ["Romance", "Musical", "Drama"], tg: ["visually-stunning", "musical-numbers", "award-winning"], p: 88 },
  { id: "eternalsunshine", t: "Eternal Sunshine of the Spotless Mind", y: 2004, g: ["Romance", "SciFi", "Drama"], tg: ["mind-bending", "indie", "award-winning"], p: 86 },
  { id: "prideandprejudice", t: "Pride & Prejudice", y: 2005, g: ["Romance", "Drama"], tg: ["feelgood", "award-winning"], p: 80 },
  { id: "beforesunrise", t: "Before Sunrise", y: 1995, g: ["Romance", "Drama"], tg: ["slow-burn", "indie"], p: 78 },
  { id: "500days", t: "(500) Days of Summer", y: 2009, g: ["Romance", "Comedy", "Drama"], tg: ["indie", "nonlinear"], p: 81 },
  { id: "whenharrymetsally", t: "When Harry Met Sally...", y: 1989, g: ["Romance", "Comedy"], tg: ["feelgood", "cult-classic"], p: 81 },
  { id: "silverlinings", t: "Silver Linings Playbook", y: 2012, g: ["Romance", "Comedy", "Drama"], tg: ["feelgood", "psychological", "award-winning"], p: 82 },
  { id: "crazyrichasians", t: "Crazy Rich Asians", y: 2018, g: ["Romance", "Comedy", "Drama"], tg: ["feelgood", "ensemble-cast"], p: 80 },
  { id: "callmebyyourname", t: "Call Me by Your Name", y: 2017, g: ["Romance", "Drama"], tg: ["coming-of-age", "slow-burn", "award-winning"], p: 81 },

  { id: "theshining", t: "The Shining", y: 1980, g: ["Horror", "Thriller"], tg: ["dark", "slow-burn", "cult-classic", "psychological"], p: 90 },
  { id: "getout", t: "Get Out", y: 2017, g: ["Horror", "Thriller", "Mystery"], tg: ["twist-ending", "psychological", "satire", "award-winning"], p: 88 },
  { id: "hereditary", t: "Hereditary", y: 2018, g: ["Horror", "Drama"], tg: ["dark", "slow-burn", "psychological"], p: 82 },
  { id: "quietplace", t: "A Quiet Place", y: 2018, g: ["Horror", "SciFi", "Thriller"], tg: ["slow-burn", "fast-paced"], p: 82 },
  { id: "conjuring", t: "The Conjuring", y: 2013, g: ["Horror", "Thriller"], tg: ["dark", "based-on-true-story"], p: 82 },
  { id: "it", t: "It", y: 2017, g: ["Horror", "Thriller"], tg: ["ensemble-cast", "coming-of-age", "dark"], p: 83 },
  { id: "psycho", t: "Psycho", y: 1960, g: ["Horror", "Thriller", "Mystery"], tg: ["twist-ending", "cult-classic", "noir"], p: 87 },
  { id: "jaws", t: "Jaws", y: 1975, g: ["Horror", "Thriller", "Adventure"], tg: ["cult-classic", "fast-paced"], p: 89 },
  { id: "exorcist", t: "The Exorcist", y: 1973, g: ["Horror"], tg: ["dark", "cult-classic", "slow-burn"], p: 85 },
  { id: "us", t: "Us", y: 2019, g: ["Horror", "Thriller", "Mystery"], tg: ["twist-ending", "psychological"], p: 78 },
  { id: "midsommar", t: "Midsommar", y: 2019, g: ["Horror", "Drama"], tg: ["dark", "slow-burn", "visually-stunning", "indie"], p: 78 },
  { id: "28dayslater", t: "28 Days Later", y: 2002, g: ["Horror", "SciFi", "Thriller"], tg: ["apocalyptic", "fast-paced"], p: 76 },
  { id: "worldwarz", t: "World War Z", y: 2013, g: ["Horror", "Action", "SciFi"], tg: ["apocalyptic", "fast-paced"], p: 74 },
  { id: "zodiac", t: "Zodiac", y: 2007, g: ["Crime", "Mystery", "Thriller"], tg: ["slow-burn", "based-on-true-story", "psychological"], p: 78 },
  { id: "shutterisland", t: "Shutter Island", y: 2010, g: ["Mystery", "Thriller", "Drama"], tg: ["twist-ending", "psychological", "dark"], p: 86 },
  { id: "parasite", t: "Parasite", y: 2019, g: ["Thriller", "Drama", "Comedy"], tg: ["twist-ending", "satire", "dark", "award-winning"], p: 91 },
  { id: "oldboy", t: "Oldboy", y: 2003, g: ["Thriller", "Mystery", "Action"], tg: ["dark", "twist-ending", "revenge", "cult-classic"], p: 80 },

  { id: "savingprivateryan", t: "Saving Private Ryan", y: 1998, g: ["War", "Drama", "Action"], tg: ["epic", "based-on-true-story", "award-winning"], p: 92 },
  { id: "schindlerslist", t: "Schindler's List", y: 1993, g: ["War", "Drama", "Biography"], tg: ["based-on-true-story", "award-winning", "dark"], p: 93 },
  { id: "dunkirk", t: "Dunkirk", y: 2017, g: ["War", "Action", "Drama"], tg: ["based-on-true-story", "fast-paced", "visually-stunning"], p: 84 },
  { id: "1917", t: "1917", y: 2019, g: ["War", "Drama", "Action"], tg: ["epic", "visually-stunning", "award-winning"], p: 85 },
  { id: "fullmetaljacket", t: "Full Metal Jacket", y: 1987, g: ["War", "Drama"], tg: ["dark", "cult-classic"], p: 82 },
  { id: "apocalypsenow", t: "Apocalypse Now", y: 1979, g: ["War", "Drama"], tg: ["epic", "dark", "slow-burn", "cult-classic"], p: 85 },
  { id: "braveheart", t: "Braveheart", y: 1995, g: ["War", "Drama", "Biography"], tg: ["epic", "based-on-true-story", "award-winning"], p: 86 },
  { id: "gladiator", t: "Gladiator", y: 2000, g: ["Action", "Drama", "War"], tg: ["epic", "revenge", "award-winning"], p: 89 },
  { id: "hacksawridge", t: "Hacksaw Ridge", y: 2016, g: ["War", "Drama", "Biography"], tg: ["based-on-true-story", "underdog"], p: 82 },
  { id: "thepianist", t: "The Pianist", y: 2002, g: ["War", "Drama", "Biography"], tg: ["based-on-true-story", "dark", "award-winning"], p: 82 },
  { id: "12yearsaslave", t: "12 Years a Slave", y: 2013, g: ["Drama", "Biography", "History"], tg: ["based-on-true-story", "dark", "award-winning"], p: 82 },

  { id: "forrestgump", t: "Forrest Gump", y: 1994, g: ["Drama", "Comedy", "Romance"], tg: ["feelgood", "epic", "award-winning"], p: 93 },
  { id: "beautifulmind", t: "A Beautiful Mind", y: 2001, g: ["Drama", "Biography"], tg: ["based-on-true-story", "psychological", "award-winning"], p: 82 },
  { id: "socialnetwork", t: "The Social Network", y: 2010, g: ["Drama", "Biography"], tg: ["based-on-true-story", "fast-paced", "award-winning"], p: 84 },
  { id: "pursuitofhappyness", t: "The Pursuit of Happyness", y: 2006, g: ["Drama", "Biography"], tg: ["based-on-true-story", "underdog", "feelgood"], p: 84 },
  { id: "whiplash", t: "Whiplash", y: 2014, g: ["Drama", "Musical"], tg: ["fast-paced", "psychological", "award-winning"], p: 87 },
  { id: "goodwillhunting", t: "Good Will Hunting", y: 1997, g: ["Drama"], tg: ["coming-of-age", "feelgood", "award-winning"], p: 87 },
  { id: "rainman", t: "Rain Man", y: 1988, g: ["Drama"], tg: ["road-trip", "award-winning"], p: 82 },
  { id: "kingsspeech", t: "The King's Speech", y: 2010, g: ["Drama", "Biography", "History"], tg: ["based-on-true-story", "award-winning"], p: 80 },
  { id: "greenbook", t: "Green Book", y: 2018, g: ["Drama", "Comedy", "Biography"], tg: ["road-trip", "based-on-true-story", "award-winning"], p: 82 },
  { id: "moonlight", t: "Moonlight", y: 2016, g: ["Drama"], tg: ["coming-of-age", "indie", "award-winning"], p: 78 },
  { id: "manchesterbythesea", t: "Manchester by the Sea", y: 2016, g: ["Drama"], tg: ["slow-burn", "dark", "award-winning"], p: 75 },
  { id: "littlemisssunshine", t: "Little Miss Sunshine", y: 2006, g: ["Comedy", "Drama"], tg: ["road-trip", "ensemble-cast", "indie", "feelgood"], p: 82 },
  { id: "chef", t: "Chef", y: 2014, g: ["Comedy", "Drama"], tg: ["feelgood", "road-trip", "indie"], p: 74 },
  { id: "ladybird", t: "Lady Bird", y: 2017, g: ["Comedy", "Drama"], tg: ["coming-of-age", "indie", "award-winning"], p: 79 },
  { id: "juno", t: "Juno", y: 2007, g: ["Comedy", "Drama"], tg: ["coming-of-age", "indie", "satire"], p: 79 },
  { id: "perksofwallflower", t: "The Perks of Being a Wallflower", y: 2012, g: ["Drama", "Romance"], tg: ["coming-of-age", "indie"], p: 78 },

  { id: "madmaxfuryroad", t: "Mad Max: Fury Road", y: 2015, g: ["Action", "SciFi", "Adventure"], tg: ["apocalyptic", "fast-paced", "visually-stunning", "award-winning"], p: 91 },
  { id: "johnwick", t: "John Wick", y: 2014, g: ["Action", "Crime", "Thriller"], tg: ["fast-paced", "revenge", "cult-classic"], p: 87 },
  { id: "diehard", t: "Die Hard", y: 1988, g: ["Action", "Thriller"], tg: ["fast-paced", "cult-classic", "underdog"], p: 89 },
  { id: "speed", t: "Speed", y: 1994, g: ["Action", "Thriller"], tg: ["fast-paced"], p: 76 },
  { id: "bourneidentity", t: "The Bourne Identity", y: 2002, g: ["Action", "Thriller", "Mystery"], tg: ["spy", "fast-paced", "twist-ending"], p: 83 },
  { id: "missionimpossiblefallout", t: "Mission: Impossible - Fallout", y: 2018, g: ["Action", "Thriller", "Adventure"], tg: ["spy", "fast-paced"], p: 87 },
  { id: "casinoroyale", t: "Casino Royale", y: 2006, g: ["Action", "Thriller", "Adventure"], tg: ["spy", "fast-paced"], p: 87 },
  { id: "skyfall", t: "Skyfall", y: 2012, g: ["Action", "Thriller", "Adventure"], tg: ["spy", "visually-stunning"], p: 86 },
  { id: "killbill1", t: "Kill Bill: Vol. 1", y: 2003, g: ["Action", "Thriller"], tg: ["revenge", "cult-classic", "fast-paced"], p: 85 },
  { id: "topgun", t: "Top Gun", y: 1986, g: ["Action", "Drama", "Romance"], tg: ["fast-paced", "cult-classic"], p: 83 },
  { id: "topgunmaverick", t: "Top Gun: Maverick", y: 2022, g: ["Action", "Drama"], tg: ["fast-paced", "feelgood", "underdog"], p: 90 },
  { id: "theraid", t: "The Raid", y: 2011, g: ["Action", "Crime", "Thriller"], tg: ["fast-paced", "indie"], p: 76 },

  { id: "greatestshowman", t: "The Greatest Showman", y: 2017, g: ["Musical", "Drama", "Biography"], tg: ["musical-numbers", "feelgood", "based-on-true-story"], p: 82 },
  { id: "chicago", t: "Chicago", y: 2002, g: ["Musical", "Crime", "Comedy"], tg: ["musical-numbers", "satire", "award-winning"], p: 76 },
  { id: "grease", t: "Grease", y: 1978, g: ["Musical", "Romance", "Comedy"], tg: ["musical-numbers", "feelgood", "cult-classic"], p: 82 },

  { id: "rocky", t: "Rocky", y: 1976, g: ["Sport", "Drama"], tg: ["underdog", "feelgood", "award-winning"], p: 88 },
  { id: "rudy", t: "Rudy", y: 1993, g: ["Sport", "Drama"], tg: ["underdog", "based-on-true-story", "feelgood"], p: 78 },
  { id: "rememberthetitans", t: "Remember the Titans", y: 2000, g: ["Sport", "Drama"], tg: ["based-on-true-story", "underdog", "feelgood"], p: 82 },
  { id: "moneyball", t: "Moneyball", y: 2011, g: ["Sport", "Drama", "Biography"], tg: ["based-on-true-story", "underdog"], p: 80 },
  { id: "creed", t: "Creed", y: 2015, g: ["Sport", "Drama"], tg: ["underdog", "feelgood"], p: 82 },

  { id: "goodthebadugly", t: "The Good, the Bad and the Ugly", y: 1966, g: ["Western", "Adventure"], tg: ["epic", "cult-classic"], p: 87 },
  { id: "djangounchained", t: "Django Unchained", y: 2012, g: ["Western", "Drama"], tg: ["revenge", "dark", "fast-paced"], p: 88 },
  { id: "truegrit", t: "True Grit", y: 2010, g: ["Western", "Drama"], tg: ["revenge", "slow-burn"], p: 78 },
  { id: "butchcassidy", t: "Butch Cassidy and the Sundance Kid", y: 1969, g: ["Western", "Adventure", "Comedy"], tg: ["cult-classic", "road-trip"], p: 79 },

  { id: "oceanseleven", t: "Ocean's Eleven", y: 2001, g: ["Crime", "Comedy", "Thriller"], tg: ["heist", "ensemble-cast", "fast-paced"], p: 86 },
  { id: "italianjob", t: "The Italian Job", y: 2003, g: ["Crime", "Action", "Thriller"], tg: ["heist", "fast-paced"], p: 78 },
  { id: "babydriver", t: "Baby Driver", y: 2017, g: ["Action", "Crime", "Thriller"], tg: ["heist", "fast-paced", "visually-stunning"], p: 83 },
  { id: "nowyouseeme", t: "Now You See Me", y: 2013, g: ["Crime", "Thriller", "Mystery"], tg: ["heist", "twist-ending"], p: 79 },

  { id: "12angrymen", t: "12 Angry Men", y: 1957, g: ["Drama", "Crime"], tg: ["courtroom", "slow-burn", "cult-classic"], p: 87 },
  { id: "fewgoodmen", t: "A Few Good Men", y: 1992, g: ["Drama", "Thriller"], tg: ["courtroom", "fast-paced"], p: 82 },

  { id: "eeaao", t: "Everything Everywhere All at Once", y: 2022, g: ["SciFi", "Comedy", "Drama", "Action"], tg: ["mind-bending", "ensemble-cast", "award-winning", "indie"], p: 90 },
  { id: "oppenheimer", t: "Oppenheimer", y: 2023, g: ["Drama", "Biography", "History"], tg: ["based-on-true-story", "epic", "award-winning", "slow-burn"], p: 90 },
  { id: "barbie", t: "Barbie", y: 2023, g: ["Comedy", "Fantasy", "Adventure"], tg: ["satire", "visually-stunning", "feelgood"], p: 88 },
  { id: "spidermannowayhome", t: "Spider-Man: No Way Home", y: 2021, g: ["Action", "SciFi", "Adventure"], tg: ["superhero", "ensemble-cast", "fast-paced"], p: 91 },
  { id: "thebatman", t: "The Batman", y: 2022, g: ["Action", "Crime", "Mystery"], tg: ["superhero", "dark", "slow-burn", "noir"], p: 85 },
  { id: "everythingeverywhere2", t: "Poor Things", y: 2023, g: ["Comedy", "Drama", "Fantasy"], tg: ["visually-stunning", "satire", "indie", "award-winning"], p: 78 },
  { id: "spiderverseacross", t: "Spider-Man: Across the Spider-Verse", y: 2023, g: ["Animation", "Action", "Adventure"], tg: ["superhero", "visually-stunning", "fast-paced"], p: 90 },
  { id: "wickedmovie", t: "Wicked", y: 2024, g: ["Musical", "Fantasy", "Drama"], tg: ["musical-numbers", "visually-stunning", "feelgood"], p: 84 },
  { id: "anora", t: "Anora", y: 2024, g: ["Comedy", "Drama"], tg: ["indie", "fast-paced", "award-winning"], p: 78 },

  { id: "legallyblonde", t: "Legally Blonde", y: 2001, g: ["Comedy", "Drama"], tg: ["underdog", "feelgood", "cult-classic"], p: 80 },
  { id: "nottinghill", t: "Notting Hill", y: 1999, g: ["Romance", "Comedy"], tg: ["feelgood", "cult-classic"], p: 78 },
  { id: "bridgetjones", t: "Bridget Jones's Diary", y: 2001, g: ["Romance", "Comedy"], tg: ["feelgood", "cult-classic"], p: 78 },
  { id: "napoleon-dynamite", t: "Napoleon Dynamite", y: 2004, g: ["Comedy"], tg: ["indie", "cult-classic", "satire"], p: 74 },
  { id: "dumbanddumber", t: "Dumb and Dumber", y: 1994, g: ["Comedy"], tg: ["road-trip", "cult-classic"], p: 78 },
  { id: "stepbrothers", t: "Step Brothers", y: 2008, g: ["Comedy"], tg: ["satire", "cult-classic"], p: 79 },
  { id: "theblindside", t: "The Blind Side", y: 2009, g: ["Sport", "Drama", "Biography"], tg: ["based-on-true-story", "feelgood", "underdog"], p: 81 },
  { id: "kungfupanda", t: "Kung Fu Panda", y: 2008, g: ["Animation", "Action", "Comedy", "Family"], tg: ["underdog", "feelgood"], p: 82 },
];
